# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/joshe/Documents/XMSS_FIPS_205_UART/xmss_fips_205_UART_vivado_project/xmss_fips_205_UART_vivado_project.srcs/sources_1/ip/sig_fifo/sig_fifo.xci
# IP: The module: 'sig_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joshe/Documents/XMSS_FIPS_205_UART/xmss_fips_205_UART_vivado_project/xmss_fips_205_UART_vivado_project.gen/sources_1/ip/sig_fifo/sig_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'sig_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/joshe/Documents/XMSS_FIPS_205_UART/xmss_fips_205_UART_vivado_project/xmss_fips_205_UART_vivado_project.gen/sources_1/ip/sig_fifo/sig_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sig_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/joshe/Documents/XMSS_FIPS_205_UART/xmss_fips_205_UART_vivado_project/xmss_fips_205_UART_vivado_project.srcs/sources_1/ip/sig_fifo/sig_fifo.xci
# IP: The module: 'sig_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joshe/Documents/XMSS_FIPS_205_UART/xmss_fips_205_UART_vivado_project/xmss_fips_205_UART_vivado_project.gen/sources_1/ip/sig_fifo/sig_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'sig_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/joshe/Documents/XMSS_FIPS_205_UART/xmss_fips_205_UART_vivado_project/xmss_fips_205_UART_vivado_project.gen/sources_1/ip/sig_fifo/sig_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sig_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
